// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD17h51GEzRLfZE7T2H8Hr-2VKypE6eeyk',
    appId: '1:138430702997:web:5ed5709e0396cb2cffc29c',
    messagingSenderId: '138430702997',
    projectId: 'recipe-app-d696e',
    authDomain: 'recipe-app-d696e.firebaseapp.com',
    databaseURL: 'https://recipe-app-d696e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipe-app-d696e.firebasestorage.app',
    measurementId: 'G-KQPXRPWG8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB74Pgq8kWTbyh5-pH1rHeCArbeijKRzg',
    appId: '1:138430702997:android:470d173f4525a4eeffc29c',
    messagingSenderId: '138430702997',
    projectId: 'recipe-app-d696e',
    databaseURL: 'https://recipe-app-d696e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipe-app-d696e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdC5-YgWySIPz-gvcNn4_DNg8q_XEXoqM',
    appId: '1:138430702997:ios:98e27a1b41a9dbbaffc29c',
    messagingSenderId: '138430702997',
    projectId: 'recipe-app-d696e',
    databaseURL: 'https://recipe-app-d696e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipe-app-d696e.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

}